
stages:
  - build
  - deploy

build:
  stage: build
  script: echo 'hello'

deploy:
  stage: deploy
  script:
    - echo 'hello'
  environment:
    name: $CI_COMMIT_REF_NAME
    url: http://dev.withwheat.wang:8082/version
  only:
    - /^master$/